### ISSUE TITLE
hardcoded paths in weathertools.py

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/experimental#1]
We are getting the icons from the hardcoded path /usr/share/pixmaps

Do the .svg files really need to be in pixmaps - or can they be in the more logical /usr/share/budgie-desktop/plugins/budgie_weathershow/icons or ~/.local/share/plugins/budgie_weathershow/icons ?

i.e. we are using libpeas so we know we can use https://lazka.github.io/pgi-docs/#Peas-1.0/classes/PluginInfo.html#Peas.PluginInfo.get_data_dir to find the data directory

**Comment by Jacob-Vlijm** [comment]
Not sure, need to find out if `GdkPixbuf.Pixbuf.new_from_file_at_size` also has a `new_from_name_at_size`. quick search...

**Comment by fossfreedom** [comment]
we can use libpeas itself to find where the plugin is installed ... and then where the data directory is.  I've done this before in my rhythmbox plugins so will go hunting for example code.

**Comment by Jacob-Vlijm** [comment]
That seems the best option, since: https://lazka.github.io/pgi-docs/GdkPixbuf-2.0/classes/Pixbuf.html shows no option at first glance, or simply use `os.path.abspath(__file__)`

**Comment by Jacob-Vlijm** [comment]
Fixed in bd6ff52
Since we need the panel icon to be symbolic, the exception is `budgie-wticon-symbolic.svg`, which we still need to be in icon path (`/usr/share/pixmaps`)
