### ISSUE TITLE
scary font on first startup

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/experimental#3]
on first install "Whoops no data available" probably should actually say "Weather location needs to be defined" ... or similar ... lol also scary big font!!

**Comment by Jacob-Vlijm** [comment]
![image](https://user-images.githubusercontent.com/8932980/40873451-7b5723a4-6660-11e8-8f66-dc99b1c526a8.png)
More civilized version

**Comment by Jacob-Vlijm** [comment]
Fixed in bd6ff52
