### ISSUE TITLE
missing next time forecast

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/experimental#4]
![workspace 1_080](https://user-images.githubusercontent.com/996240/40925665-28ac2556-6812-11e8-9d14-023b7c76cac0.png)
Note the time of the clock - and then the first forecast - 21:00 - not sure why - 18:00 is missing.

**Comment by Jacob-Vlijm** [comment]
I left it out on purpose, 18:00 should be about your current time, which is on the desktop.

**Comment by fossfreedom** [comment]
think it would be more consistent to be in the popup - BTW - my desktop looks like this.  No weather there

![workspace 1_081](https://user-images.githubusercontent.com/996240/40928062-472b6af4-6818-11e8-9408-4461bebe020c.png)

**Comment by Jacob-Vlijm** [comment]
Hmm, could you restart the panel and show the output in case it happens again? Something must have broken /usr/lib/.... /weathershow.

**Comment by fossfreedom** [comment]
ah - after restarting the panel I noticed that it appeared on the desktop - but after a few seconds it 
disappeared never to come back.  No errors reported in the terminal other than this

```
(weathershow:5990): dbind-WARNING **: 17:21:57.255: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

```

**Comment by Jacob-Vlijm** [comment]
What if you run it directly?

**Comment by fossfreedom** [comment]
`./weathershow &` makes it appear on the desktop - and it doesnt disappear again.

**Comment by Jacob-Vlijm** [comment]
OK, should be fixed now in panelrunner. Could you confirm?

**Comment by Jacob-Vlijm** [comment]
This look ok. It is not exactly predictable what OWM shows in the current range though, but now the first item in the overview is the first in the json output. Don't like the British weather though :)

**Comment by fossfreedom** [comment]
lol
