### ISSUE TITLE
searching issues

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/experimental#5]
![workspace 1_085](https://user-images.githubusercontent.com/996240/40969492-efeaadca-68af-11e8-8459-77903bb7e295.png)

Doesn't matter what I type in the box nothing appears to be found when I click the search button - as you can see there looks to be the beginnings of a drop-down menu but nothing in it.

At the very least, the drop down should say something like "City not found" - but not sure why nothing can be searched for

**Comment by Jacob-Vlijm** [comment]
Huh? 
Does the file `~/.config/budgie-extras/weathershow/cities.txt` exist?

**Comment by fossfreedom** [comment]
yes - lots of cities listed in there.

I tried again to find London and a popup with london stuff appeared.  But I've just tried several times again and nothing appears other than that screenshot "partial" popup

**Comment by Jacob-Vlijm** [comment]
With other non-matches, or existing ones?

**Comment by fossfreedom** [comment]
ah - got it - it is case sensitive. The search should be case-insensitive

**Comment by Jacob-Vlijm** [comment]
You're annoying :)

**Comment by Jacob-Vlijm** [comment]
Both should be fixed now.
