### ISSUE TITLE
missing units?

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/experimental#6]
![selection_086](https://user-images.githubusercontent.com/996240/40999956-5e451e46-6904-11e8-9219-21ba767dfa92.png)

What is that last number - 1015?  Is the atmospheric pressure?  Think the unit for this is millibar 

I note that the forecast or daily doesnt have this number.  Deliberate or oversight?

**Comment by Jacob-Vlijm** [comment]
Kind of deliberate, I wanted to keep the info on the time series brief. Personally I was mostly interested in sky state, temp and wind. Unit should be added. Own sais hpa, but I don't know that unit?

**Comment by Jacob-Vlijm** [comment]
Ok, turns out it is hectopascal, equals millibar. Will add the unit to the info.

**Comment by Jacob-Vlijm** [comment]
obsolete, since we replaced the pressure label by the humidity label (which has a unit).
